server:
  port: 8080
  servlet:
    context-path: '/'

spring:
  application:
    name: rummy-card-game
  main:
    allow-circular-references: true

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/rummy_app
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate # Use validate with Flyway
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    # cleanDisabled: false

  # Jackson Configuration
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: NON_NULL

  # WebSocket Configuration
  websocket:
    sockjs:
      client-library-url: /webjars/sockjs-client/1.5.1/sockjs.min.js
    # Max text message buffer size
    max-text-message-buffer-size: 8192
    # Max binary message buffer size
    max-binary-message-buffer-size: 8192
    # Message size limit
    max-message-size: 65536

# Security Configuration
security:
  jwt:
    token:
      # secret-key: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
      # Token valid for 10 days
      expire-length: 864000000

# Logging Configuration
logging:
  level:
    org.springframework.web.filter.CorsFilter: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.web.socket: DEBUG
    com.andi.rummy: DEBUG # Your application package
    org.hibernate.SQL: DEBUG
    # For detailed SQL parameter logging (use cautiously in production)
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
  packages-to-scan: com.andi.rummy.controllers
  paths-to-match: /api/**

# Custom Application Properties
app:
  cors:
    allowed-origins: http://localhost:5173
  game:
    # Maximum players per game
    max-players: 4
    # Initial hand size
    initial-hand-size: 14
    # Minimum points required for first meld
    min-first-meld-points: 51
    # Timeout in minutes for inactive games
    inactive-timeout: 30
